### ISSUE TITLE
[Feature Request] 迁移到 vue 并启用前端路由

### ISSUE THREAD

**Issue by Wybxc** [HanHan233/PhiCommunity-Bak#29]
利用 vue 可以实现 #24 所说的工程化，并且 vue 的前端路由功能可以大幅降低页面切换时的时间消耗。

vue 实现 UI，canvas 绘图实现游戏功能，这种模式已经被很多现代网页游戏采用。

**Comment by Wybxc** [comment]
不过，比起 vue，我本人更加熟悉 React，但是从纯 html + js 迁移到 React 的破坏性太大，几乎相当于完全重写，而迁移到 vue 则是相对容易一些的。所以，在这方面，我可能起不到帮助。

**Comment by HanHan233** [comment]
我们已经有成员正在着手进行工程化了

**Comment by Wybxc** [comment]
也许我可以 fork 一份，然后用 React 重写一下试试（不过能不能做出来就是另一回事了）（逃

**Comment by Wybxc** [comment]
> 我们已经有成员正在着手进行工程化了

目前进展如何？

**Comment by HanHan233** [comment]
> > 我们已经有成员正在着手进行工程化了
> 
> 目前进展如何？

目前应该是只套了个webpack我看？
https://github.com/ZreXoc/PhiCommunity

**Comment by ZreXoc** [comment]
> > 我们已经有成员正在着手进行工程化了
> 
> 目前进展如何？

目前是我在负责，但由于一些原因近期没有换成框架的打算。即使用了框架 组件的复用程度应该也比较低

另，我也只会react，不会vue(

**Comment by HanHan233** [comment]
此仓库即将封存，请前往最新仓库[点此前往](https://github.com/HanHan233/PhiCommunity)
